export const SET_COLLECTIONS_LOADING = 'SET_COLLECTIONS_LOADING';
export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS';
export const SET_COLLECTIONS_ERROR = 'SET_COLLECTIONS_ERROR';
export const ADD_DATA_TO_FIREBASE = 'ADD_DATA_TO_FIREBASE';


