export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START';
export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const FACEBOOK_SIGN_IN_START = 'FACEBOOK_SIGN_IN_START';
export const GITHUB_SIGN_IN_START = 'GITHUB_SIGN_IN_START';

export const CHECK_USER_SESSION = 'CHECK_USER_SESSION';

export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const SIGN_OUT_START = 'SIGN_OUT_START';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
